name 'ubuntu_rsyslog'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ubuntu_rsyslog'
long_description 'Installs/Configures ubuntu_rsyslog'
version '0.1.4'
